In [2]:
import pandas as pd
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

In [3]:
boston_data =  pd.read_csv("BostonHousing.csv")
boston_data.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [4]:
boston_data.describe()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [5]:
y = boston_data.medv

In [6]:
X = boston_data.drop(["medv"],axis=1)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8)

In [16]:
X_train.shape, y_test.shape

((404, 13), (102,))

In [17]:
X_train.shape, y_train.shape

((404, 13), (404,))

In [10]:
boston_model = linear_model.LinearRegression()

In [11]:
boston_model.fit(X_train, y_train)

LinearRegression()

In [12]:
y_predict = boston_model.predict(X_test)

In [15]:
print("Coefficients:", boston_model.coef_)
print("Intercept: ", boston_model.intercept_)
print("Mean Squared Error : %.2f " % mean_squared_error(y_test, y_predict))
print("Coefficient of determination (R Square score): %.2F" % r2_score(y_test, y_predict))

Coefficients: [-1.10525852e-01  3.78913176e-02  5.29054904e-02  3.15212413e+00
 -1.98536663e+01  3.65710253e+00 -3.18534446e-04 -1.38375527e+00
  3.24312950e-01 -1.27501165e-02 -9.87692294e-01  8.61897718e-03
 -5.11472335e-01]
Intercept:  38.609959240831245
Mean Squared Error : 20.80
Coefficient of determination (R Square score): 0.79